# Generated by Django 2.2.5 on 2020-05-27 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200527_0946'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='email_secrete',
            new_name='email_secret',
        ),
    ]
